#!/usr/bin/python

import sys
import os
import collections
import bson
import json
import fileinput
sys.path.append(".")

for line in fileinput.input():
  data = bson.BSON.encode( json.loads(line) )
  sys.stdout.write(data)
