#!/usr/bin/python
import sys
import matplotlib.pyplot as plt
import csv
import os

if len(sys.argv) < 4 or not sys.argv[1] in ['points', 'result']:
	print "Usage: plotpoints (points|result) <src-file> <output-file-prefix>[:dpi]"
	sys.exit(1)

inFile = sys.argv[1]
inFile = sys.argv[2]
outFile = sys.argv[3].split(":")[0]
dpi=600

if len(sys.argv[3].split(":")) == 2:
	dpi = int(sys.argv[3].split(":")[1])

inFileName = os.path.splitext(os.path.basename(inFile))[0]



########### READ DATA

cs = []
xs = []
ys = []

minX = None
maxX = None
minY = None
maxY = None

colors = map( lambda x: str(x), range(50))

colors[0] = 'black'
colors[1] = '#1f77b4'
colors[2] = '#ff7f0e'
colors[3] = '#2ca12c'
colors[4] = '#986cc0'
colors[5] = '#d62728'
colors[6] = '#2ca02c'
colors[7] = '#662ca0'
colors[8] = '#a02c2c'
colors[9] = '#339933'
colors[10]= '#a02c83'
colors[11]= '#ff3333'

print inFile

if sys.argv[1] == 'points':
	fig = plt.figure()
	ax1 = fig.add_subplot(111)

	with open(inFile, 'rb') as file:
		for line in file:
			# parse data
			csvData = line.strip().split(' ')

			x = float(csvData[0])
			y = float(csvData[1])

			if not minX or minX > x:
				minX = x
			if not maxX or maxX < x:
				maxX = x
			if not minY or minY > y:
				minY = y
			if not maxY or maxY < y:
				maxY = y

			xs.append(x)
			ys.append(y)

		# plot data
		ax1.scatter(xs, ys, s=25, c="#5b5b5b", edgecolors='None', alpha=0.5)

	if len(sys.argv) >= 5:
		cs1=[]
		xs1=[]
		ys1=[]
		centroids = sys.argv[4]

		with open(centroids, 'rb') as file:
			for line in file:
				# parse data
				csvData = line.strip().split(' ')

				c = int(csvData[0])
				x = float(csvData[1])
				y = float(csvData[2])

				cs1.append(colors[c])
				xs1.append(x)
				ys1.append(y)

			# plot data
			ax1.scatter(xs1, ys1, s=250, c=cs1, alpha=1.0)


elif sys.argv[1] == 'result':
	fig = plt.figure()
	ax1 = fig.add_subplot(111)

	with open(inFile, 'rb') as file:
		for line in file:
			# parse data
			csvData = line.strip().split(' ')

			c = int(csvData[0])
			x = float(csvData[1])
			y = float(csvData[2])

			cs.append(colors[c])
			xs.append(x)
			ys.append(y)

		# plot data
		ax1.scatter(xs, ys, s=25, c=cs, edgecolors='None', alpha=0.3)

	if len(sys.argv) == 5:
		cs1=[]
		xs1=[]
		ys1=[]
		centroids = sys.argv[4]

		with open(centroids, 'rb') as file:
				for line in file:
						# parse data
						csvData = line.strip().split(' ')

						c = int(csvData[0])
						x = float(csvData[1])
						y = float(csvData[2])

						# colors[c]
						cs1.append('black')
						xs1.append(x)
						ys1.append(y)

				# plot data
				ax1.scatter(xs1, ys1, s=150, c=cs1, edgecolors='k', alpha=1.0)

	
plt.savefig(outFile, dpi=dpi, bbox_inches='tight' )

print "\nPlotted file: %s" % outFile

sys.exit(0)
