#!/usr/bin/python
import sys

import matplotlib.pyplot as plt
from numpy.random import rand
from PIL import Image
from os.path import basename


import matplotlib.pyplot as plt
import numpy as np

counts = []
dim_x = 0
dim_y = 0
input = sys.argv[1]

with open(input, 'rb') as file:
		for line in file:
				# parse data
				freq = line.strip().split(' ')

				counts.append( map( lambda x:int(x), freq ) )
				dim_x = max( len(freq), dim_x)
				dim_y+=1

img = np.zeros((dim_x,dim_y))
for (yi,y) in enumerate(counts):
	for (xi,f) in enumerate(y):
		img[xi,yi] = f

plt.matshow(img)

if len( sys.argv) > 2:
	out = sys.argv[2]
	plt.savefig(out)
else:
	plt.show()
