#!/bin/bash

# DEFAULT VALUES
SKETCH_HH=100
SKETCH_SIZE_DELTA="0.5 0.1 0.05 0.01"
SKETCH_SIZE_EPSILON="0.1 0.01 0.001 0.0001"
DPI=100
FORMAT=png
TITLE=
SKIP_LEARNING="--skip-learning"
ITERATIONS=100
ENUM_HH=""

# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to > 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -d|--dataset-dir)
    DATA_DIR="$2"
    shift # past argument
    ;;
    -p|--sketch-p)
    SKETCH_P="$2"
    shift # past argument
    ;;
    -D|--sketch-delta)
    SKETCH_SIZE_DELTA="$2"
    shift # past argument
    ;;
    -E|--sketch-epsilon)
    SKETCH_SIZE_EPSILON="$2"
    shift # past argument
    ;;
    -h|--heavy-hitters)
    SKETCH_HH="$2"
    shift # past argument
    ;;
    -R|--image-resolution)
    DPI="$2"
    shift # past argument
    ;;
    -e|--learn-enumeration)
    ENUM_HH="$ENUM_HH --enumeration"
    shift # past argument
    ;;
    -e|--learn-hh)
    ENUM_HH="$ENUM_HH --heavyhitters"
    shift # past argument
    ;;
    -f|--format)
    FORMAT="$2"
    shift # past argument
    ;;
    -t|--title)
    TITLE="$2"
    shift # past argument
    ;;
    -G|--generate-results)
	SKIP_LEARNING=""
    shift # past argument
    ;;
    -I|--iterations)
	ITERATIONS="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

# cleanup
# we do not cleanup. we assume the dataset was generated
# rm -r ${DATA_DIR}

# prepare folders
mkdir -p ${DATA_DIR}/dataset
mkdir -p ${DATA_DIR}/sketch

# generate sample dataset
# NUM_SAMPLES=50000
# NUM_CENTROIDS=3
# resolution of the generated dataset
# RESOLUTION=2
# sketch size parameters
# resolution of the projected input-space
# SKETCH_P=2
# number of heavy hitters
# START=$(date +%s)

# -------------------------------
# perform flink kmeans
# -------------------------------

echo "FLINK: start running Flink KMeans"
blos examples run eu.blos.java.ml.clustering.FlinkKMeans \
		${DATA_DIR}/dataset/points \
		${DATA_DIR}/dataset/good_centers \
		${DATA_DIR}/flink/out/points/ \
		${ITERATIONS} \
		${DATA_DIR}/flink/out/centers/
		 &> /dev/null

cat ${DATA_DIR}/flink/out/points/* >> ${DATA_DIR}/flink/result
cat ${DATA_DIR}/flink/out/centers/* >> ${DATA_DIR}/flink/centers

blos visualize plotpoints result ${DATA_DIR}/flink/result ${DATA_DIR}/flink/result ${DATA_DIR}/flink/centers


IFS=', ' read -r -a LIST_SKETCH_SIZE_DELTA <<< "$SKETCH_SIZE_DELTA"
IFS=', ' read -r -a LIST_SKETCH_SIZE_EPSILON <<< "$SKETCH_SIZE_EPSILON"
for d in "${LIST_SKETCH_SIZE_DELTA[@]}"
do
	for e in "${LIST_SKETCH_SIZE_EPSILON[@]}"
	do
		SKETCH_SIZE="${d}:${e}"
		SKETCH_FILE=${d}_${e}

		rm -r ${DATA_DIR}/sketch/${SKETCH_FILE}
		mkdir ${DATA_DIR}/sketch/${SKETCH_FILE}

		echo "scatterplot for $SKETCH_SIZE into $SKETCH_FILE"

		NUM_CENTERS=$(cat ${DATA_DIR}/dataset/real_centers|wc -l)

		if [ -z "$SKIP_LEARNING" ]; then
			echo "execute sketched-kmeans with $NUM_CENTERS centers"
		fi

		if [ -z "$ENUM_HH" ]; then
			echo "run learning using heavyhitters"
		fi

		echo "build sketch..."
		exec 5>&1
		OUT=$(blos examples run eu.blos.java.ml.clustering.SketchedKMeans ${SKIP_LEARNING} ${ENUM_HH} \
				-i ${DATA_DIR}/dataset/points \
				-o ${DATA_DIR}/sketch/${SKETCH_FILE} \
				--init-file ${DATA_DIR}/dataset/good_centers \
				-k $NUM_CENTERS \
				-n $ITERATIONS \
				-p ${SKETCH_P}  \
				-s ${SKETCH_SIZE} \
				--num-heavyhitters ${SKETCH_HH} \
				--discover-inputspace \
				--print-sketch \
				--verbose \
				|tee >(cat - | grep "" >&5))


		# read output parameters
		PARAM_SIZE=$(echo 	"$OUT"|grep 	"size(mb)="| awk -F "=" '{print $2}')
		PARAM_D=$(echo 		"$OUT"|grep 	"d="| awk -F "=" '{print $2}')
		PARAM_W=$(echo 		"$OUT"|grep 	"w="| awk -F "=" '{print $2}')


		DESC="delta:$d,epsilon:$e,size:$PARAM_SIZE,w:$PARAM_W,d:$PARAM_D"
		echo "sketch details $DESC"
		echo "plotting..."
		blos visualize sketch-inputspace \
				-i ${DATA_DIR}/sketch/${SKETCH_FILE}/enumerated-input-space \
				--output="${DATA_DIR}/sketch/${SKETCH_FILE}/enumerated-input-space-${SKETCH_FILE}" \
				-f ${FORMAT} \
				-C \
				-d ${DPI}

		blos visualize sketch-inputspace \
				-i ${DATA_DIR}/sketch/${SKETCH_FILE}/hh-input-space \
				--output="${DATA_DIR}/sketch/${SKETCH_FILE}/hh-input-space-${SKETCH_FILE}" \
				-f ${FORMAT} \
				-C \
				-d ${DPI}

		# compute nearest centers for each data point
		blos visualize apply-centroids ${DATA_DIR}/sketch/${SKETCH_FILE}/centers-enum ${DATA_DIR}/dataset/points >  "${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-enum-${SKETCH_FILE}"

		# compute nearest centers for each data point
		blos visualize apply-centroids ${DATA_DIR}/sketch/${SKETCH_FILE}/centers-hh ${DATA_DIR}/dataset/points >  "${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-hh-${SKETCH_FILE}"


		# plot datapoints with its computed centers using enumeration
		blos visualize plotpoints result \
			${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-enum-${SKETCH_FILE}  \
			${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-enum-plot-${SKETCH_FILE}.${FORMAT}:${DPI} \
			${DATA_DIR}/sketch/${SKETCH_FILE}/centers-enum

		# plot datapoints with its computed centers using heavyhitters
		blos visualize plotpoints result \
			${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-hh-${SKETCH_FILE}  \
			${DATA_DIR}/sketch/${SKETCH_FILE}/sketch-result-hh-plot-${SKETCH_FILE}.${FORMAT}:${DPI} \
			${DATA_DIR}/sketch/${SKETCH_FILE}/centers-hh
	done
done

# merge images into a scatterplot
# montage ${DATA_DIR}/sketch/*/*.png \
#	-title "${TITLE}" \
#	-tile $(( ${#LIST_SKETCH_SIZE_EPSILON[@]}*3 ))x${#LIST_SKETCH_SIZE_DELTA[@]} \
#	-geometry +0+0 \
#	 ${DATA_DIR}/sketch/sketch-scatterplot.eps