#!/bin/bash


# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to > 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -d|--data-dir)
    DATA_DIR="$2"
    shift # past argument
    ;;
    -s|--number-samples)
    NUM_SAMPLES="$2"
    shift # past argument
    ;;
    -c|--number-centroids)
    NUM_CENTROIDS="$2"
    shift # past argument
    ;;
    -r|--resolution)
    RESOLUTION="$2"
    shift # past argument
    ;;
    -p|--sketch-p)
    SKETCH_P="$2"
    shift # past argument
    ;;
    -D|--sketch-delta)
    SKETCH_SIZE_DELTA="$2"
    shift # past argument
    ;;
    -E|--sketch-epsilon)
    SKETCH_SIZE_EPSILON="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

# cleanup
rm -r ${DATA_DIR}

# prepare folders
mkdir -p ${DATA_DIR}/dataset
mkdir -p ${DATA_DIR}/sketch

# generate sample dataset
NUM_SAMPLES=50000
NUM_CENTROIDS=3
STDDEV=0.04
# resolution of the generated dataset
RESOLUTION=2
# range for the generated dataset
RANGE=1.0
# sketch size parameters
SKETCH_SIZE_DELTA="0.5 0.1 0.05 0.01"
SKETCH_SIZE_EPSILON="0.1 0.01 0.001 0.0001"
# resolution of the projected input-space
SKETCH_P=2
# number of heavy hitters
SKETCH_HH=100
START=$(date +%s)
ITERATIONS=0
SEED=3

# generate data
blos examples run eu.blos.java.ml.clustering.KMeansDatasetGenerator \
	-points ${NUM_SAMPLES} \
	-k ${NUM_CENTROIDS} \
	-stddev ${STDDEV} \
	-range ${RANGE} \
	-output ${DATA_DIR}/dataset \
	-resolution ${RESOLUTION} \
	-seed ${SEED}

IFS=', ' read -r -a LIST_SKETCH_SIZE_DELTA <<< "$SKETCH_SIZE_DELTA"
IFS=', ' read -r -a LIST_SKETCH_SIZE_EPSILON <<< "$SKETCH_SIZE_EPSILON"
for d in "${LIST_SKETCH_SIZE_DELTA[@]}"
do
	for e in "${LIST_SKETCH_SIZE_EPSILON[@]}"
	do
		SKETCH_SIZE="${d}:${e}"
		SKETCH_FILE=${d}_${e}
		echo "scatterplot for $SKETCH_SIZE into $SKETCH_FILE"
		mkdir ${DATA_DIR}/sketch/${SKETCH_FILE}
		OUT=$(blos examples run eu.blos.java.ml.clustering.SketchedKMeans \
				-i ${DATA_DIR}/dataset/points \
				-o ${DATA_DIR}/sketch/${SKETCH_FILE} \
				-k ${NUM_CENTROIDS} \
				-n ${ITERATIONS} \
				-p ${SKETCH_P}  \
				-s ${SKETCH_SIZE} \
				-H ${SKETCH_HH} \
				--skip-learning \
				--print-sketch)

		# read output parameters
		PARAM_SIZE=$(echo 	"$OUT"|grep 	"size(mb)="| awk -F "=" '{print $2}')
		PARAM_D=$(echo 		"$OUT"|grep 	"d="| awk -F "=" '{print $2}')
		PARAM_W=$(echo 		"$OUT"|grep 	"w="| awk -F "=" '{print $2}')

		DESC="delta=${d},epsilon=${e},size=${$PARAM_SIZE},w=${PARAM_W},d=${PARAM_D}"
		blos visualize sketch-inputspace \
				-i ${DATA_DIR}/sketch/${SKETCH_FILE}/reconstructed-input-space \
				-o ${DATA_DIR}/sketch/${SKETCH_FILE}/reconstructed-input-space \
				-t "${DESC}" \
				-f png
		#		-d 600
	done
done

# merge images into a scatterplot
montage ${DATA_DIR}/sketch/*/reconstructed-input-space.png -title "" -geometry +0+0 ${DATA_DIR}/sketch/sketch-scatterplot.png
