#!/usr/bin/env python

import sys
import json

jsonList = []

# input comes from STDIN (standard input)
for line in sys.stdin:
  line = line.strip()
  obj =  json.loads( line )
  jsonList.append( obj )                                                                                                          

sortedList = sorted(jsonList, key=lambda x: x['_id'], reverse=True)
for s in sortedList:
  sys.stdout.write( json.dumps( s, sort_keys=True) )
  sys.stdout.write("\n")
